.github/pull_request_template.md, README.md
- Add a pull request template to make PRs more uniform
- Check out `.github/pull_request_template.md`
=> Add pull request template

prisma/schema.prisma, src/app/page.tsx, tailwind.config.ts
Closes [#12](https://github.com/sandboxnu/cooper/issues/12)
Implements designed database schema + next auth tables in schema.prisma
=> #12 Added Prisma Schema for DB + NextAuth

.husky/commit-msg, .husky/pre-commit, .husky/prepare-commit-msg, commitlint.config.ts, package.json, pnpm-lock.yaml
- Set up linting of staged files and enforce [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)
=> Add Git Hooks

prisma/schema.prisma, src/server/api/root.ts, src/server/api/routers/review.ts, src/server/api/routers/reviewRouter.ts
BREAKING CHANGE: Changes the schema to add reviews to companies.
- Adds a `reviewRouter` for doing CRUD operations on `Review`
=> Add Review Router

src/server/api/root.ts, src/server/api/routers/profile.ts, src/server/api/routers/profileRouter.ts
- Adds a `profileRouter` for doing CRUD operations on `Profile`
=> Add Profile Router

src/schema/company.ts, src/schema/misc.ts, src/schema/profile.ts, src/schema/review.ts, src/schema/role.ts, src/server/api/routers/company.ts, src/server/api/routers/profile.ts, src/server/api/routers/review.ts, src/server/api/routers/role.ts
Move schemas to a different directory so that they can be reused by the front-end forms.
=> Move `Zod` schemas to separate directories

README.md, components.json, package.json, pnpm-lock.yaml, src/app/(protected)/review/page.tsx, src/app/layout.tsx, src/components/review-form.tsx, src/components/ui/button.tsx, src/components/ui/form.tsx, src/components/ui/input.tsx, src/components/ui/label.tsx, src/components/ui/textarea.tsx, src/lib/utils.ts, src/styles/globals.css, tailwind.config.ts
Closes #31 
Adds the review section of the form as per the Figma. See the `/review` route.
~- Still a work in progress - React hydration blows up for some reason.~
=> Add Review Co-op Form Section

src/server/auth.ts
- Adds a mock `CredentialsProvider` to fix authentication in Vercel Previews
=> Add Mock Credential Provider

src/components/form/review-form.tsx
=> Fix Coerce For Hourly Pay

apps/web/src/app/_components/reviews/review-card.tsx
=> Fix Review Card UI Bug

.github/workflows/ci.yml, README.md, apps/docs/docs/02-technology.mdx, apps/web/test/app.test.ts, package.json, pnpm-lock.yaml, pnpm-workspace.yaml, vitest.workspace.ts
Closes #67 
Add [Vitest](https://vitest.dev/) 🤓 and a GitHub Action to run along with other CI checks.
=> [WIP] Add Vitest Testing Framework

apps/web/src/app/(pages)/(dashboard)/companies/page.tsx, apps/web/src/app/(pages)/(dashboard)/roles/page.tsx, apps/web/src/app/_components/footer.tsx, apps/web/src/app/_components/header-layout.tsx
Closes #78
Changes:
scroll through the jobs side bar now! Wow!
temporary footer bc we needed the legal disclaimer for the company photo api or whatever
Will prob need to replaced with something designers cook up
There are some changes from april too (???)
must have never merged, think it was a hotfix we were just running during showcase
=> [78] Footer and Scrolling

apps/web/src/app/(pages)/(dashboard)/roles/page.tsx, packages/api/package.json, packages/api/tests/mocks/review.ts, packages/api/tests/review.test.ts, packages/api/tsconfig.json, turbo.json
@gpalmer27 's ticket 🥇 
See #92 
Includes tests for the API calls for filtering.
Closes #73 
All the tests pass!
=> Cooper Testing is CURSED

packages/api/src/router/review.ts
Runs a check on how many reviews a user has submitted before creating a new one, throws error if they hit the cap of 5.
Prevents users from submitting too many reviews, since each person can realistically complete no more than 5 experiences.
Closes #108 
Created 5 reviews on a fresh account and saw them appear in drizzle studio. Attempted to create a 6th, did not show up in drizzle.
=> Max 5 Reviews Per User

README.md
spent about 18 hours testing this
=> Add Documentation Link to README.md

apps/web/src/app/_components/header.tsx
checks if a profile has made 5 reviews, if it has it does not render create new review button
prevents users from creating more than 5 reviews
Closes #113
=> removed button when profile has 5 reviews

.github/pull_request_template.md, .github/workflows/migration.yml, README.md, packages/db/package.json, turbo.json
Add a GitHub Action workflow for running migrations on the production database (only for changes to `main`). 
To reduce "points of failure" (forgot to run `pnpm db:generate`, forgot to run `pnpm db:migrate` on the production database, accidentally forgot to switch back to development database, etc).
Lemme think about this one 😛 
Edit: Made it so that the CI also runs on all pull requests (temporarily) and spent half an hour trying to fix the `Missing POSTGRES_URL` only to realize that it is supposed to be a **Repository Secret** and not an Actions Secret (which still doesn't make sense to me but it works?).
=> Add Migration CI

apps/web/src/app/(pages)/(protected)/review/page.tsx, apps/web/src/app/_components/form/review-form.tsx, apps/web/src/app/_components/form/sections/ratings-section.tsx, apps/web/src/app/_components/form/sections/review-section.tsx, apps/web/src/app/_components/form/submission-confirmation.tsx, apps/web/src/app/_components/form/submission-failure.tsx, apps/web/src/app/_components/reviews/role-info.tsx
The mobile form is now mobile responsive ◡̈ !!!
( to access it pick a roleId and go to /review?id={roleId} )
Welcome Page:
Form Pages Examples:
Success / Failure Pages:
=> Make form mobile responsive

apps/web/src/app/(pages)/(protected)/layout.tsx, apps/web/src/app/(pages)/(protected)/profile/page.tsx, apps/web/src/app/(pages)/(protected)/review/page.tsx, apps/web/src/app/_components/header.tsx, apps/web/src/app/_components/profile/profile-button.tsx, apps/web/src/app/_components/reviews/new-review-dialogue.tsx, apps/web/src/app/_components/reviews/review-card.tsx, packages/db/src/schema/companies.ts, packages/db/src/schema/locations.ts, packages/ui/src/dropdown-menu.tsx
Profile page now exists (click on profile)
=> Profile Page

packages/api/src/router/review.ts, packages/api/src/trpc.ts, packages/api/tests/review.test.ts
Added an endpoint for calculating the averages across an entire industry. Also changed the caching for this information to 8 hours.
Helpful for finding industry-specific data
Closes #170 
I actually wrote tests!!
Added a test to the review.test.ts file from last semester
- [ x] New feature (non-breaking change which adds functionality)
- [ x] My code follows the code style of this project.
- [ x] I have moved the ticket to "In Review"
- [x ] I have added reviewers to this PR
- [ x] I have added tests to cover my changes.
- [ x] All new and existing tests passed.
=> Industry average endpoint

apps/web/src/app/(pages)/(dashboard)/(roles)/page.tsx, apps/web/src/app/(pages)/(dashboard)/companies/page.tsx, packages/api/src/router/role.ts
Fuzzy searching now works on the frontend again.
Closes #174
manually
=> 174 Fuzzy Searching on Frontend

apps/web/src/app/_components/reviews/role-info.tsx
=> Add Review Button

apps/web/src/app/_components/search/search-filter.tsx
=> fixed searching

apps/web/src/app/_components/form/sections/review-section.tsx, apps/web/src/app/_components/location.tsx, apps/web/src/app/_components/reviews/new-review/new-company-content.tsx, apps/web/src/app/_components/reviews/role-info.tsx, apps/web/src/app/_components/search/company-search-bar.tsx
Abstracted location combobox and fixed bug with location box after switching between different parts of the website.
No more bug during cooper live demo!
Closes #[ticket]
Clicked through the website over and over again
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] My code follows the code style of this project.
- [ x] I have added reviewers to this PR
=> Location search fix

apps/web/src/app/(pages)/(dashboard)/(roles)/page.tsx, apps/web/src/app/(pages)/(dashboard)/(roles)/role/page.tsx, apps/web/src/app/(pages)/(dashboard)/companies/company/page.tsx, apps/web/src/app/(pages)/(dashboard)/companies/page.tsx, apps/web/src/app/(pages)/(protected)/profile/page.tsx, apps/web/src/app/_components/combo-box.tsx, apps/web/src/app/_components/companies/all-company-roles.tsx, apps/web/src/app/_components/companies/company-reviews.tsx, apps/web/src/app/_components/form/sections/ratings-section.tsx, apps/web/src/app/_components/form/sections/review-section.tsx, apps/web/src/app/_components/header-layout.tsx, apps/web/src/app/_components/header.tsx, apps/web/src/app/_components/location.tsx, apps/web/src/app/_components/onboarding/constants/index.ts, apps/web/src/app/_components/reviews/new-review/new-company-content.tsx, apps/web/src/app/_components/reviews/review-card.tsx, apps/web/src/app/_components/reviews/role-card-preview.tsx, apps/web/src/app/_components/reviews/role-info.tsx, apps/web/src/app/_components/screen-size-indicator.tsx, apps/web/src/app/_components/search/company-search-bar.tsx, apps/web/src/app/_components/search/search-filter.tsx, apps/web/src/app/_components/shared/star-graph.tsx, apps/web/src/app/layout.tsx
make cooper mobile responsive
users wanna review on their phones!
=> Mobile Responsiveness.

packages/api/src/router/company.ts
Fixed the bug with filtering on the company page so now it's possible to filter by industry and location at the same time.
Closes #[ticket]
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] My code follows the code style of this project.
- [ x] I have added reviewers to this PR
=> Fixed company filtering

apps/web/src/app/(pages)/(dashboard)/(roles)/page.tsx, apps/web/src/app/_components/combo-box.tsx, apps/web/src/app/_components/search/company-search-bar.tsx
Made company filters on one line for mobile and fixed the search bar url routing for the roles page.
Closes #215 
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] My code follows the code style of this project.
- [x ] I have added reviewers to this PR
=> Updated roles url and mobile company filter

apps/web/src/app/(pages)/(dashboard)/(roles)/page.tsx, packages/api/src/router/role.ts, packages/ui/src/index.ts, packages/ui/src/pagination.tsx
Implemented pagination for roles 
tried to simulate what NuWork has, implemented pagination in db router as well as the frontend pages
Note: Currently, the number of roles per page is set to 2, so I can see my code in action. I only have 5 roles and I got lazy to figure out the seeding for now (might do it later)
Note: When we are waiting for the data for the new page, we render the "loading..." page. It kind of looks ugly, but also, people wouldn't spend all their time clicking if there were, like, 20 roles in the scroll so it should be fine? I took a look at how nuwork does it - they just leave the screen blank in the mean time. 
Closes #221
=> review scrolling pagination
